Import('RTT_ROOT')
Import('rtconfig')
from building import *
#print("Hello spiffs")
#print(GetCurrentDir())

cwd = GetCurrentDir()

#print(cwd)


src = Glob("*.c")

CPPPATH = [cwd]

group = DefineGroup('littlefs', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
