# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
group = []
list  = os.listdir(cwd)


if rtconfig.CPU == "bonfire":
    group = SConscript(os.path.join('common', 'SConscript'))
    group = group + SConscript(os.path.join(rtconfig.CPU, 'SConscript'))

else:

    # add common code files
    if   rtconfig.CPU == "e9xx" :
        group = group
    elif rtconfig.CPU == "nuclei" :
        group = group
    elif rtconfig.CPU == "virt64" :
        group = group
    else :
        group = group + SConscript(os.path.join(cwd, 'common', 'SConscript'))

    # cpu porting code files
    if  rtconfig.CPU == "e9xx" :
        group = group + SConscript(os.path.join(cwd, rtconfig.VENDOR, rtconfig.CPU, 'SConscript'))
    else :
        group = group + SConscript(os.path.join(cwd, rtconfig.CPU, 'SConscript'))

Return('group')
