from building import *
import os

cwd     = GetCurrentDir()

src     = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

group += SConscript(os.path.join(cwd,'littlefs','SConscript'))

Return('group')
